name: LotteryS
author: '１５４１２'
main: org.c15412.Plugin2.Lottery.MainClass
version: '1.2.0'
api-version: '1.16'

commands:
  彩票:
    description: '购买彩票'
    usage: '/彩票 [十个数字(不想选的可以输入R)]'
    aliases:
      - '买彩票'
      - 'cp'
      - 'lottery'
      - 'lt'
      - 'lotterytickets'
      - '彩票开奖'
      - '开奖'



